

export const subjects=[
    {
        subject:'ინგლისური',
        subjectId:1
    },
    {
        subject:'ქართული',
        subjectId:2
    },
     {
        subject:'მათემატიკა',
        subjectId:3
    },
    {
        subject:'ქიმია',
        subjectId:4
    },
    {
        subject:'ფიზიკა',
        subjectId:5
    },
    {
        subject:'ბიოლოგია',
        subjectId:6
    },
    {
        subject:'სპორტი',
        subjectId:7
    }
]

export const weeks=[
    {
        week:'პირველი',
        weekId:1
    },
    {
        week:'მეორე',
        weekId:2
    },
    {
        week:'მესამე',
        weekId:3
    }
]
export const days=[
    {
        day:'ორშაბათი',
        dayId:1
    },
    {
        day:'სამშაბათი',
        dayId:2
    },
    {
        day:'ოთხშაბათი',
        dayId:3
    },
    {
        day:'ხუთშაბათი',
        dayId:4
    },
    {
        day:'პარასკევი',
        dayId:5
    },
]

export const students=[
    {
        studentId:1,
        name:'ხატია ჩუბინიძე',
        weeks:[
            {
              week:'პირველი',
              days:[
                {
                            day:'ორშაბათი',
                            subject:[
                                {
                                    sub:'ინგლისური',
                                    subjectId:1,
                                    grade:[0]
                                },
                                {
                                    sub:'ქართული',
                                    subjectId:2,
                                    grade:[3]
                                },
                                {
                                    sub:'მათემატიკა',
                                    subjectId:3,
                                    grade:[5]
                                },
                                {
                                    sub:'ქიმია',
                                    subjectId:4,
                                    grade:[6]
                                },
                                {
                                    sub:'ფიზიკა',
                                    subjectId:5,
                                    grade:[7]
                                },
                                {
                                    sub:'ბიოლოგია',
                                    subjectId:6,
                                    grade:[8]
                                },
                                {
                                    sub:'სპორტი',
                                    subjectId:7,
                                    grade:[10]
                                },

                            ]
                        },
                        {
                            day:'სამშაბათი',
                            subject:[
                                {
                                    sub:'ინგლისური',
                                    subjectId:1,
                                    grade:[9]
                                },
                                {
                                    sub:'ქართული',
                                    subjectId:2,
                                    grade:[10]
                                },
                                {
                                    sub:'მათემატიკა',
                                    subjectId:3,
                                    grade:[7]
                                },
                                {
                                    sub:'ქიმია',
                                    subjectId:4,
                                    grade:[10]
                                },
                                {
                                    sub:'ფიზიკა',
                                    subjectId:5,
                                    grade:[8]
                                },
                                {
                                    sub:'ბიოლოგია',
                                    subjectId:6,
                                    grade:[5]
                                },
                                {
                                    sub:'სპორტი',
                                    subjectId:7,
                                    grade:[10]
                                }
                            ]
                        },
                        {
                            day:'ოთხშაბათი',
                            subject:[
                                {
                                    sub:'ინგლისური',
                                    subjectId:1,
                                    grade:[9]
                                },
                                {
                                    sub:'ქართული',
                                    subjectId:2,
                                    grade:[10]
                                },
                                {
                                    sub:'მათემატიკა',
                                    subjectId:3,
                                    grade:[7]
                                },
                                {
                                    sub:'ქიმია',
                                    subjectId:4,
                                    grade:[10]
                                },
                                {
                                    sub:'ფიზიკა',
                                    subjectId:5,
                                    grade:[8]
                                },
                                {
                                    sub:'ბიოლოგია',
                                    subjectId:6,
                                    grade:[5]
                                },
                                {
                                    sub:'სპორტი',
                                    subjectId:7,
                                    grade:[10]
                                },
                            ]
                        },
                        {
                            day:'ხუთშაბათი',
                            subject:[
                                {
                                    sub:'ინგლისური',
                                    subjectId:1,
                                    grade:[9]
                                },
                                {
                                    sub:'ქართული',
                                    subjectId:2,
                                    grade:[10]
                                },
                                {
                                    sub:'მათემატიკა',
                                    subjectId:3,
                                    grade:[7]
                                },
                                {
                                    sub:'ქიმია',
                                    subjectId:4,
                                    grade:[10]
                                },
                                {
                                    sub:'ფიზიკა',
                                    subjectId:5,
                                    grade:[8]
                                },
                                {
                                    sub:'ბიოლოგია',
                                    subjectId:6,
                                    grade:[5]
                                },
                                {
                                    sub:'სპორტი',
                                    subjectId:7,
                                    grade:[10]
                                },]
                        },
                        {
                            day:'პარასკევი',
                            subject:[
                                {
                                    sub:'ინგლისური',
                                    subjectId:1,
                                    grade:[9]
                                },
                                {
                                    sub:'ქართული',
                                    subjectId:2,
                                    grade:[10]
                                },
                                {
                                    sub:'მათემატიკა',
                                    subjectId:3,
                                    grade:[7]
                                },
                                {
                                    sub:'ქიმია',
                                    subjectId:4,
                                    grade:[10]
                                },
                                {
                                    sub:'ფიზიკა',
                                    subjectId:5,
                                    grade:[8]
                                },
                                {
                                    sub:'ბიოლოგია',
                                    subjectId:6,
                                    grade:[5]
                                },
                                {
                                    sub:'სპორტი',
                                    subjectId:7,
                                    grade:[10]
                                },]
                        
                   
                    
                }
              ]
            },
           


            
                {
                  week:'მეორე',
                  days:[
                    {
                                day:'ორშაბათი',
                                subject:[
                                    {
                                        sub:'ინგლისური',
                                        subjectId:1,
                                        grade:[9]
                                    },
                                    {
                                        sub:'ქართული',
                                        subjectId:2,
                                        grade:[10]
                                    },
                                    {
                                        sub:'მათემატიკა',
                                        subjectId:3,
                                        grade:[7]
                                    },
                                    {
                                        sub:'ქიმია',
                                        subjectId:4,
                                        grade:[10]
                                    },
                                    {
                                        sub:'ფიზიკა',
                                        subjectId:5,
                                        grade:[8]
                                    },
                                    {
                                        sub:'ბიოლოგია',
                                        subjectId:6,
                                        grade:[5]
                                    },
                                    {
                                        sub:'სპორტი',
                                        subjectId:7,
                                        grade:[10]
                                    },
    
                                ]
                            },
                            {
                                day:'სამშაბათი',
                                subject:[
                                    {
                                        sub:'ინგლისური',
                                        subjectId:1,
                                        grade:[9]
                                    },
                                    {
                                        sub:'ქართული',
                                        subjectId:2,
                                        grade:[10]
                                    },
                                    {
                                        sub:'მათემატიკა',
                                        subjectId:3,
                                        grade:[7]
                                    },
                                    {
                                        sub:'ქიმია',
                                        subjectId:4,
                                        grade:[10]
                                    },
                                    {
                                        sub:'ფიზიკა',
                                        subjectId:5,
                                        grade:[8]
                                    },
                                    {
                                        sub:'ბიოლოგია',
                                        subjectId:6,
                                        grade:[5]
                                    },
                                    {
                                        sub:'სპორტი',
                                        subjectId:7,
                                        grade:[10]
                                    }
                                ]
                            },
                            {
                                day:'ოთხშაბათი',
                                subject:[
                                    {
                                        sub:'ინგლისური',
                                        subjectId:1,
                                        grade:[9]
                                    },
                                    {
                                        sub:'ქართული',
                                        subjectId:2,
                                        grade:[10]
                                    },
                                    {
                                        sub:'მათემატიკა',
                                        subjectId:3,
                                        grade:[7]
                                    },
                                    {
                                        sub:'ქიმია',
                                        subjectId:4,
                                        grade:[10]
                                    },
                                    {
                                        sub:'ფიზიკა',
                                        subjectId:5,
                                        grade:[8]
                                    },
                                    {
                                        sub:'ბიოლოგია',
                                        subjectId:6,
                                        grade:[5]
                                    },
                                    {
                                        sub:'სპორტი',
                                        subjectId:7,
                                        grade:[10]
                                    },
                                ]
                            },
                            {
                                day:'ხუთშაბათი',
                                subject:[
                                    {
                                        sub:'ინგლისური',
                                        subjectId:1,
                                        grade:[9]
                                    },
                                    {
                                        sub:'ქართული',
                                        subjectId:2,
                                        grade:[10]
                                    },
                                    {
                                        sub:'მათემატიკა',
                                        subjectId:3,
                                        grade:[7]
                                    },
                                    {
                                        sub:'ქიმია',
                                        subjectId:4,
                                        grade:[10]
                                    },
                                    {
                                        sub:'ფიზიკა',
                                        subjectId:5,
                                        grade:[8]
                                    },
                                    {
                                        sub:'ბიოლოგია',
                                        subjectId:6,
                                        grade:[5]
                                    },
                                    {
                                        sub:'სპორტი',
                                        subjectId:7,
                                        grade:[10]
                                    },]
                            },
                            {
                                day:'პარასკევი',
                                subject:[
                                    {
                                        sub:'ინგლისური',
                                        subjectId:1,
                                        grade:[9]
                                    },
                                    {
                                        sub:'ქართული',
                                        subjectId:2,
                                        grade:[10]
                                    },
                                    {
                                        sub:'მათემატიკა',
                                        subjectId:3,
                                        grade:[7]
                                    },
                                    {
                                        sub:'ქიმია',
                                        subjectId:4,
                                        grade:[10]
                                    },
                                    {
                                        sub:'ფიზიკა',
                                        subjectId:5,
                                        grade:[8]
                                    },
                                    {
                                        sub:'ბიოლოგია',
                                        subjectId:6,
                                        grade:[5]
                                    },
                                    {
                                        sub:'სპორტი',
                                        subjectId:7,
                                        grade:[10]
                                    },]
                          
                        
                    }
                  ]
                },
               



                    {
                      week:'მესამე',
                      days:[
                        {
                                    day:'ორშაბათი',
                                    subject:[
                                        {
                                            sub:'ინგლისური',
                                            subjectId:1,
                                            grade:[9]
                                        },
                                        {
                                            sub:'ქართული',
                                            subjectId:2,
                                            grade:[10]
                                        },
                                        {
                                            sub:'მათემატიკა',
                                            subjectId:3,
                                            grade:[7]
                                        },
                                        {
                                            sub:'ქიმია',
                                            subjectId:4,
                                            grade:[10]
                                        },
                                        {
                                            sub:'ფიზიკა',
                                            subjectId:5,
                                            grade:[8]
                                        },
                                        {
                                            sub:'ბიოლოგია',
                                            subjectId:6,
                                            grade:[5]
                                        },
                                        {
                                            sub:'სპორტი',
                                            subjectId:7,
                                            grade:[10]
                                        },
        
                                    ]
                                },
                                {
                                    day:'სამშაბათი',
                                    subject:[
                                        {
                                            sub:'ინგლისური',
                                            subjectId:1,
                                            grade:[9]
                                        },
                                        {
                                            sub:'ქართული',
                                            subjectId:2,
                                            grade:[10]
                                        },
                                        {
                                            sub:'მათემატიკა',
                                            subjectId:3,
                                            grade:[7]
                                        },
                                        {
                                            sub:'ქიმია',
                                            subjectId:4,
                                            grade:[10]
                                        },
                                        {
                                            sub:'ფიზიკა',
                                            subjectId:5,
                                            grade:[8]
                                        },
                                        {
                                            sub:'ბიოლოგია',
                                            subjectId:6,
                                            grade:[5]
                                        },
                                        {
                                            sub:'სპორტი',
                                            subjectId:7,
                                            grade:[10]
                                        }
                                    ]
                                },
                                {
                                    day:'ოთხშაბათი',
                                    subject:[
                                        {
                                            sub:'ინგლისური',
                                            subjectId:1,
                                            grade:[9]
                                        },
                                        {
                                            sub:'ქართული',
                                            subjectId:2,
                                            grade:[10]
                                        },
                                        {
                                            sub:'მათემატიკა',
                                            subjectId:3,
                                            grade:[7]
                                        },
                                        {
                                            sub:'ქიმია',
                                            subjectId:4,
                                            grade:[10]
                                        },
                                        {
                                            sub:'ფიზიკა',
                                            subjectId:5,
                                            grade:[8]
                                        },
                                        {
                                            sub:'ბიოლოგია',
                                            subjectId:6,
                                            grade:[5]
                                        },
                                        {
                                            sub:'სპორტი',
                                            subjectId:7,
                                            grade:[10]
                                        },
                                    ]
                                },
                                {
                                    day:'ხუთშაბათი',
                                    subject:[
                                        {
                                            sub:'ინგლისური',
                                            subjectId:1,
                                            grade:[9]
                                        },
                                        {
                                            sub:'ქართული',
                                            subjectId:2,
                                            grade:[10]
                                        },
                                        {
                                            sub:'მათემატიკა',
                                            subjectId:3,
                                            grade:[7]
                                        },
                                        {
                                            sub:'ქიმია',
                                            subjectId:4,
                                            grade:[10]
                                        },
                                        {
                                            sub:'ფიზიკა',
                                            subjectId:5,
                                            grade:[8]
                                        },
                                        {
                                            sub:'ბიოლოგია',
                                            subjectId:6,
                                            grade:[5]
                                        },
                                        {
                                            sub:'სპორტი',
                                            subjectId:7,
                                            grade:[10]
                                        },]
                                },
                                {
                                    day:'პარასკევი',
                                    subject:[
                                        {
                                            sub:'ინგლისური',
                                            subjectId:1,
                                            grade:[9]
                                        },
                                        {
                                            sub:'ქართული',
                                            subjectId:2,
                                            grade:[10]
                                        },
                                        {
                                            sub:'მათემატიკა',
                                            subjectId:3,
                                            grade:[7]
                                        },
                                        {
                                            sub:'ქიმია',
                                            subjectId:4,
                                            grade:[10]
                                        },
                                        {
                                            sub:'ფიზიკა',
                                            subjectId:5,
                                            grade:[8]
                                        },
                                        {
                                            sub:'ბიოლოგია',
                                            subjectId:6,
                                            grade:[5]
                                        },
                                        {
                                            sub:'სპორტი',
                                            subjectId:7,
                                            grade:[10]
                                        },]
                            
                        }
                      ]
                    }
        ]
    },
    {
        studentId:2,
        name:'ლილი სისვაძე',
        grades:[
            {
                sub:'',
                grade:[9]
            }
        ]
    },
    {
        studentId:3,
        name:'ელენე ელბაქიძე',
        grades:[
            {
                sub:'',
                grade:[9]
            }
        ]
    },
]
